Lab4: main.o AnimalPen.o FarmAnimal.o Cow.o Chicken.o CyberChicken.o
	g++ -Wall -std=c++11 -g main.o AnimalPen.o FarmAnimal.o Cow.o Chicken.o CyberChicken.o -o Lab4
AnimalPen.o: AnimalPen.cpp
	g++ -Wall -std=c++11 -g -c AnimalPen.cpp
FarmAnimal.o: FarmAnimal.cpp
	g++ -Wall -std=c++11 -g -c FarmAnimal.cpp
Cow.o: Cow.cpp
	g++ -Wall -std=c++11 -g -c Cow.cpp
Chicken.o: Chicken.cpp
	g++ -Wall -std=c++11 -g -c Chicken.cpp
CyberChicken.o: CyberChicken.cpp
	g++ -Wall -std=c++11 -g -c CyberChicken.cpp
main.o: main.cpp StackInterface.h Stack.h Node.h Stack.hpp Node.hpp
	g++ -Wall -std=c++11 -g -c main.cpp
